[package]
name = "apynext"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.23.0"
shuttle-runtime = "0.23.0"
shuttle-shared-db = { version = "0.23.0", features = ["postgres-rustls"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "postgres"] }
tokio = "1.28.2"
