CREATE TABLE IF NOT EXISTS email_confirm (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(320) UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '5 minutes',
    token VARCHAR(256) NOT NULL UNIQUE
)