CREATE TABLE IF NOT EXISTS Post (
  id BIGSERIAL PRIMARY KEY,
  author_id BIGSERIAL NOT NULL,
  FOREIGN KEY (author_id) REFERENCES Account(id) ON DELETE CASCADE,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
