CREATE TABLE IF NOT EXISTS post (
  id BIGSERIAL PRIMARY KEY,
  author BIGSERIAL NOT NULL,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
