CREATE TABLE IF NOT EXISTS post (
  id BIGSERIAL PRIMARY KEY,
  author_id BIGSERIAL NOT NULL,
  FOREIGN KEY (author_id) REFERENCES account(id),
  title VARCHAR(50) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
